language: r
cache: packages
warnings_are_errors: false
r:
  - release
before_install:
  - tlmgr install index
r_packages:
  - covr
env:
  - ON_TRAVIS = 1
after_success:
  - Rscript -e 'library(covr); codecov()'

